### ISSUE TITLE
Just doesn't work for me (Windows 10 1803)

### ISSUE THREAD

**Issue by HoldYourWaffle** [Teamwork/node-afk#21]
I can't put it any other way, it just doesn't work (meaning it doesn't trigger any events no matter what I do).

### Code (basically the example in the readme):
```js
const NodeAFK = require('afk');

const inactivityDuration = 10 * 1000;
const afk = new NodeAFK(inactivityDuration);

afk.init();

afk.on('status:idle', () => {
	console.log("Now idle");
});

afk.on('status:active', () => {
	console.log("Now active");
});

afk.on('status-changed', ({ previousStatus, currentStatus }) => {
	console.log(`${previousStatus} -> ${currentStatus}`);
});
```

I had some initial problems with installing because I'm a total n00b and didn't set up node-gys properly, but that's resolved now (by installing the VS build tools). Varying in poll rate didn't help, however if I set the `inactivityDuration` to 0 it triggers the 'Now idle' message _once_.
I'm at a loss at how to fix this.

### System:
```
Edition: Windows 10 Education
Version: 1803
Build: 17134.345
```

I'll be happy to provide more information if necessary.

**Comment by smithalan92** [comment]
Hey @HoldYourWaffle 

Sorry for the delay, I completely missed this until now. I've ran your above sample code, and it works as expected for me. At a guess I'd say the issue is from an improperly built native module.

If you're still having this issue, maybe try removing your node modules folder and installing the dependencies fresh.

You can also see if any errors are being emitted using

```js
afk.on('error', (err) => console.log(err));
```
